version: '3.8'

services:

  api:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    container_name: api
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
    volumes: 
      - ./:/app


  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    ports:                                                                                                              
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data: